### ISSUE TITLE
Проблемы использования

### ISSUE THREAD

**Issue by AlexAdm1** [khorevaa/v8rac#8]
Добрый день.
При попытке использования данной библиотеки наткнулся на некоторое непонимание либо на ошибки.

1. При получении Таблицы баз по методу УправлениеКластером.СписокИнформационныхБаз(), метод возвращает задвоенный перечень информационных баз.
2. При попытке получить ПодробноеОписаниеИБ = УправлениеКластером.ПолучитьПодробноеОписаниеИнформационнойБазы(СтрокаТаблицаИб.Имя,АторизацияИБ) появляется ошибка недостаточно прав.
3. При сборе строки подключения вручную (просто из командной строки собрал строку) передавал собранную строку в функцию ВыполнитьКоманду все отрабатывает.
Подскажите в чем может быть проблема?

**Comment by khorevaa** [comment]
Вам необходимо влить к себе вот этот PR https://github.com/khorevaa/v8rac/pull/7

**Comment by khorevaa** [comment]
По пункту 1.. Нужен пример.

**Comment by AlexAdm1** [comment]
Привет.

Подскажите, а как правильней залить к себе изменение параметров? Доступа вроде как нет на редактирование библиотек в GIT?


Вот такой код при исполнении выдает задвоенные строки в результат.

`#Использовать v8rac
// #Использовать irac
// #Использовать v8Find
#Использовать 1commands

АдресСервера = "localhost";
ВерсияПлатформы = "8.3.13.1513";

УправлениеКластером = Новый УправлениеКластером;
УправлениеКластером.УстановитьКластер(АдресСервера);
УправлениеКластером.Подключить();

ТаблицаИБ =  УправлениеКластером.СписокИнформационныхБаз();
Для Каждого СтрокаТаблицаИб Из ТаблицаИБ Цикл
  Сообщить(Строка(СтрокаТаблицаИб.Имя) + " - " + Строка(СтрокаТаблицаИб.UID) + " - " + 
  Строка(СтрокаТаблицаИб.Кластер));   
КонецЦикла;`

Кусок результат
For_RIB_ZUP_test - ed130cab-96d8-49ab-b5b7-6892c72946d3 - 3c083b0a-6ec7-4ab7-8905-dced1e3ea2ab
For_RIB_ZUP_test - ed130cab-96d8-49ab-b5b7-6892c72946d3 - 3c083b0a-6ec7-4ab7-8905-dced1e3ea2ab

**Comment by khorevaa** [comment]
1. Скачать ветку develop и распаковать туда где лежит либа
2.  Похоже у Вас задвоился кластер. Выведете результат СписокЛокальныхКластеров()  должен быть 1 кластер.

**Comment by AlexAdm1** [comment]
Выводил, выводит в списке кластеров один кластер

**Comment by AlexAdm1** [comment]
читал код библиотеки там получается такое впечатление что с индексами какая то беда, но понять какая именно не могу

**Comment by AlexAdm1** [comment]
После обновления библиотеки. ПолучениеИнформации по БД начало работать, остался момент с задвоенными строками Таблицы значений по Информационным Базам в Кластере.
И есть еще момент возможно ли при невозможности авторизоваться в БД для получения информации по БД как то обрабатывать такие моменты в виде сообзения и продолжать обработку дальше? Что-то типа сообщение "Авторизация к БД не удалась пропускаем"?

**Comment by khorevaa** [comment]
Да нашел проблему. С индексом.. Туда добавляются базы по UID и наименованию для быстрого поиска..... Надо подумать что.... делать

**Comment by AlexAdm1** [comment]
Спасибо. 
Пока я только начал работы с библиотеками на 1Script, так что думаю пока разберусь что к чему у Вас получиться придумать решение.
