### ISSUE TITLE
Опечатка в модуле УправлениеКластером.os в процедурах Установки и снятия блокировки информационных баз. 

### ISSUE THREAD

**Issue by MVK80** [khorevaa/v8rac#9]
В процедуре БлокировкаИнформационнойБазы у соответствия ПараметрыИнформационнойБазы записан несуществующий для соответствия метод Добавить():
Если ЗначениеЗаполнено(АвторизацияИБ.Пароль) Тогда
				ПараметрыИнформационнойБазы.Добавить("--infobase-pwd", ОбернутьВКавычки(АвторизацияИБ.Пароль)); 
КонецЕсли;

Надо бы исправить на Вставить(), как и применяется ниже и выше этой опечатки! 

Такая же опечатка в процедуре СнятьБлокировкуИнформационнойБазы.

**Comment by khorevaa** [comment]
Сделает PR?

**Comment by MVK80** [comment]
Ни разу не делал еще. Пока нет времени пробовать это.

**Comment by khorevaa** [comment]
Исправлено в релизе 0.2.2
